
services:
  api:
    container_name: studyandchill-api
    build:
      context: .
      dockerfile: src/StudyAndChill.API/DockerFile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - JWT_SECRET=${JWT_SECRET}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - ASAAS_API_KEY=${ASAAS_API_KEY}
      - ASAAS_URL=${ASAAS_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: studyandchill_db
    environment:
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: